import propTypes from 'prop-types'
// import { Inter } from 'next/font/google'

import '#/node_modules/minireset.css/minireset.min.css'
import './globals.css'

import { Providers } from '@/components/Provider'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Fundacite Aragua',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { session, ...params },
}) {
  return (
    <Providers session={session}>
      <html lang="es">
        <body
        // className={inter.className}
        >
          {children}
        </body>
      </html>
    </Providers>
  )
}

RootLayout.propTypes = {
  children: propTypes.node.isRequired,
  params: propTypes.shape({ session: propTypes.object }),
}
